"""cuenta y movimiento_cuenta

Revision ID: 1047950d32c3
Revises: 
Create Date: 2026-08-27 10:33:58.291472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1047950d32c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('EFECTIVO', 'CUPO_REVOLVENTE', 'FONDO_FIJO', 'RED_RECAUDACION', name='tipo_cuenta', native_enum=False), nullable=False),
    sa.Column('saldo_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_inicial_dia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cupo_transaccional', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cupo_utilizado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('movimiento_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DEPOSITO', 'RETIRO', 'USO', 'AJUSTE', name='tipo_movimiento', native_enum=False), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_cuenta_cuenta_id'), 'movimiento_cuenta', ['cuenta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimiento_cuenta_cuenta_id'), table_name='movimiento_cuenta')
    op.drop_table('movimiento_cuenta')
    op.drop_table('cuenta')
    # ### end Alembic commands ###
