"""directorio

Revision ID: 16a0c16602b3
Revises: 2b1deb20bc04
Create Date: 2026-08-27 11:06:26.841891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a0c16602b3'
down_revision: Union[str, Sequence[str], None] = '2b1deb20bc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EMPRESA', 'CLIENTE', name='tipo_directorio', native_enum=False), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('red', sa.String(length=100), nullable=True),
    sa.Column('cedula_cuenta', sa.String(length=50), nullable=True),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directorio')
    # ### end Alembic commands ###
