"""proveedor_comision y transaccion_comision

Revision ID: 2b1deb20bc04
Revises: 0f7ecce4985e
Create Date: 2026-08-27 11:02:16.648083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1deb20bc04'
down_revision: Union[str, Sequence[str], None] = '0f7ecce4985e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('comision_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aplica_iva', sa.Boolean(), nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('transaccion_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_recibir', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comision', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_sobre_comision', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_cobrado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor_comision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaccion_comision_proveedor_id'), 'transaccion_comision', ['proveedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaccion_comision_proveedor_id'), table_name='transaccion_comision')
    op.drop_table('transaccion_comision')
    op.drop_table('proveedor_comision')
    # ### end Alembic commands ###
