"""servicio y escalon_precio

Revision ID: 3d956ace3c11
Revises: 1047950d32c3
Create Date: 2026-08-27 10:42:18.970555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d956ace3c11'
down_revision: Union[str, Sequence[str], None] = '1047950d32c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('tipo_precio', sa.Enum('FIJO', 'ESCALONADO', 'VARIABLE', name='tipo_precio', native_enum=False), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalon_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_desde', sa.Integer(), nullable=False),
    sa.Column('cantidad_hasta', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalon_precio_servicio_id'), 'escalon_precio', ['servicio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalon_precio_servicio_id'), table_name='escalon_precio')
    op.drop_table('escalon_precio')
    op.drop_table('servicio')
    # ### end Alembic commands ###
