"""arqueo_caja, arqueo_detalle y conteo_monedas

Revision ID: da4f748d5219
Revises: 3d956ace3c11
Create Date: 2026-08-27 10:48:49.680470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4f748d5219'
down_revision: Union[str, Sequence[str], None] = '3d956ace3c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arqueo_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saldo_apertura', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_cierre', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ganancia_neta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estado_arqueo', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteo_monedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('denominaciones', sa.JSON(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arqueo_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arqueo_id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['arqueo_id'], ['arqueo_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arqueo_detalle_arqueo_id'), 'arqueo_detalle', ['arqueo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arqueo_detalle_arqueo_id'), table_name='arqueo_detalle')
    op.drop_table('arqueo_detalle')
    op.drop_table('conteo_monedas')
    op.drop_table('arqueo_caja')
    # ### end Alembic commands ###
